os: windows
language: node_js
node_js: '10'
install:
  - npm install --global yarn
  - npm update node-sass@latest
  - npm install electron --save-dev
  - yarn add electron-builder --dev
  - npm install electron-packager --save-dev
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
  - set DEBUG=electron-builder
  - yarn dist
  - dir
  - node deletelock.js
  - dir
  - npm uninstall --global yarn
