os: windows
language: node_js
node_js: '10'
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - npm update node-sass@latest
  - npm install electron --save-dev
  - npm install electron-builder --save-dev
  - npm install electron-packager --save-dev
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
  - yarn dist
  - dir
deploy:
  provider: releases
  api_key: "fa6b7c0bc13031da888ef89d39acd18645130c4b"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  draft: true
  on:
    tags: true
