os: windows
language: node_js
node_js: '10'
install:
  - npm install --global yarn
  - npm update node-sass@latest
  - npm install electron --save-dev
  - npm install electron-builder --save-dev
  - npm install electron-packager --save-dev
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
  - set DEBUG=electron-builder
  - npm run dist
  - dir
deploy:
  provider: releases
  api_key: "75155d69f8b57bfb39d051682affdee31a57ed63"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  draft: true
  on:
    tags: true
