sudo: required
dist: xenial
language: node_js
node_js: '10'
before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt-get update
  - sudo apt-get install -y aptitude
  - sudo aptitude install -y winehq-stable
install:
  - npm install --global yarn
  - npm install electron --save-dev
  - yarn add electron-builder --dev
  - npm install electron-packager --save-dev
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
script:
  - set DEBUG=electron-builder
  - node deletepackage.js
  - yarn dist-win --publish "never"
  - dir
  - node deletelock.js
  - dir
  - npm uninstall --global yarn
deploy:
  provider: releases
  api_key: "50c254662d290e179b48"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
