os: windows
language: node_js
node_js: '10'
install:
  - npm update node-sass@latest
  - npm install electron --save-dev
  - npm install electron-builder --save-dev
  - npm install electron-packager --save-dev
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  draft: true
  on:
    tags: true
