sudo: required
dist: xenial
language: node_js
node_js: '10'
before_install:
  - sudo apt install build-essential
  - sudo snap install --classic snapcraft
  - sudo apt-get install --no-install-recommends -y libopenjp2-tools
  - sudo apt-get install --no-install-recommends -y snapcraft
  - sudo apt-get install build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python-dbusmock openjdk-8-jre
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt-get update
  - sudo apt-get install -y aptitude
  - sudo aptitude install -y winehq-stable
install:
  - npm install --global yarn
  - npm install electron --save-dev
  - npm uninstall electron-builder --save-dev
  - yarn global add electron-builder
  - npm install jquery --save-dev
  - npm install webpack --save-dev
  - npm install async --save
  - npm install oauth-electron-facebook --save
  - npm install run-async --save
  - npm install --global release-it
script:
  - set DEBUG=electron-builder
  - npm uninstall async --save
  - npm uninstall run-async --save
  - cat package.json
  - rm -rf docs
  - cd img
  - rm -f saoxnew.psd
  - rm -f footer_bg.png
  - rm -f footer.png
  - dir
  - cd -
  - electron-builder -wl --publish "never"
  - dir
  - node deletepackage.js
  - dir
  - npm uninstall --global yarn
  - cd dist
  - dir
  - cd -
  - release-it 1.5.3 --config .release-it.json --no-npm.publish --no-git
