name: Build/release Beta

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
  - cron: 0 0 * * 5

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      #- run: npm view saox version >> ${{ env.betalevel }}
      
      #- run: npm version ${{ env.betalevel }}-beta
      
      #- name: Extract version
      #  id: extract_version
      #  uses: Saionaro/extract-package-version@v1.0.6
        
      #- name: Print version
      #  run: echo ${{ steps.extract_version.outputs.version }}
        
      #- run: git config --global user.email "boy1556@hotmail.com"
      #- run: git config --global user.name "Your Name"
        
      #- run: npm version ${{ steps.extract_version.outputs.version }}-beta
      
      #- run: npm view saox version

      - run: node prere.js

      - name: Minecraft Custom Tag
        id: mctagcustom
        uses: boyphongsakorn/minecraft-beta-version-style@v1.15

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.mctagcustom.outputs.betaversion }}
      
      - run: npm version ${{ steps.mctagcustom.outputs.betaversion }}
          
      - run: sudo dpkg --add-architecture i386
        if: matrix.os == 'ubuntu-latest'
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-latest'
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt install --install-recommends winehq-stable
        if: matrix.os == 'ubuntu-latest'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/') }}
          
          skip_build: true
