name: Build/release Beta

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
  - cron: 0 0 * * 5

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        
      - run: echo ${{steps.package-version.outputs.current-version}}
      
      - run: npm version ${{steps.package-version.outputs.current-version}}-beta
      
      - run: echo ${{steps.package-version.outputs.current-version}}
          
      - run: sudo dpkg --add-architecture i386
        if: matrix.os == 'ubuntu-latest'
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-latest'
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt install --install-recommends winehq-stable
        if: matrix.os == 'ubuntu-latest'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/') }}
          
          skip_build: true
