name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - run: sudo dpkg --add-architecture i386
        if: matrix.os == 'ubuntu-latest'
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-latest'
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt install --install-recommends winehq-stable
        if: matrix.os == 'ubuntu-latest'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
          
          skip_build: true
  onlysnap:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
        - i386
        - amd64
        - armhf
        - arm64
        - ppc64el
        - s390x

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - run: sudo dpkg --add-architecture i386
        if: matrix.os == 'ubuntu-latest'
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-latest'
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt install --install-recommends winehq-stable
        if: matrix.os == 'ubuntu-latest'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}
          
      - uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt@sha256:df15403e06a03c2f461c1f7938b171fda34a5849eb63a70e2a2109ed5a778bde

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
          
          skip_build: true

          args: '--linux snap'
