name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - run: sudo dpkg --add-architecture i386
        if: matrix.os == 'ubuntu-latest'
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-latest'
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt install --install-recommends winehq-stable
        if: matrix.os == 'ubuntu-latest'
        
      - run: npm update
      
      - run: npm i -g electron-builder

      - name: Build/release Electron app
        run: npm run distandpuhall --if-present
