# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo dpkg --add-architecture i386
    - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
    - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
    - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
    - run: sudo apt install --install-recommends winehq-stable
    - run: npm ci
    - run: npm run dist-win
    - run: npm test
