# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - run: sudo apt update
    - run: sudo apt install build-essential
    - run: sudo apt install snapd
    - run: sudo snap install --classic snapcraft
    - run: sudo snap refresh
    - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools
    - run: sudo apt-get install --no-install-recommends -y snapcraft
    - run: sudo apt-get install build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python-dbusmock openjdk-8-jre
    - run: sudo dpkg --add-architecture i386
    - run: wget -nc https://dl.winehq.org/wine-builds/winehq.key
    - run: sudo apt-key add winehq.key
    - run: sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
    - run: sudo apt-get update
    - run: sudo apt-get install -y aptitude
    - run: sudo aptitude install -y winehq-stable
    - run: bash <(curl http://getvcn.codenotary.io -L)
    - run: npm i -D electron@latest
    - run: electron-builder -l --publish "always" -c.snap.publish=github
    - run: electron-builder install-app-deps
